server:
  port: 8080
#  servlet:
#    context-path: /softwareblog

github:
  client_id: d32754e05783c716a028
  client_secret: 418a4b711aa998ee8bd9adcc76259b13bf1b0df4
#  redirect_url: http://18.130.87.161:8080/callback
  redirect_url: http://localhost:8080/callback

per_page: 20
per_page_detail: 10


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://18.130.87.161:3306/blog?characterEncoding=utf8&useSSL=false
    username: root
    password: blog123
#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.swareblog.softwareblog.vo
  mapperLocations: classpath:mapper/*Mapper.xml